use_frameworks!

target 'Savvy_Example' do
  pod 'Savvy', :path => '../'

#  target 'Savvy_Tests' do
#    inherit! :search_paths
#    
#pod 'Savvy', :path => '../'
#    pod 'Quick'
#    pod 'Nimble'
#  end
end
